# Generated by Django 4.2.4 on 2023-08-07 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='type',
            old_name='type',
            new_name='document_type',
        ),
    ]
